#! /usr/bin/env bash
# Copyright 2019- <fastype.org>
# Apache License Version 2.0


OS="Unknown-OS"
ROOT=`pwd`
case "$OSTYPE" in
  solaris*) OS="Solaris" ;;
  darwin*)  OS="MacOSX" ;; 
  linux*)   OS="Linux" ;;
  bsd*)     OS="BSD" ;;
  *)        echo "[fastype] Unknown *$OSTYPE* Not Support!" && exit 3 ;;
esac
echo "[fastype] Build for $OS"

git submodule update --init --recursive
echo [fastype] prepare spdlog v1.3.1
cd $ROOT/src/spdlog && git checkout tags/v1.3.1 && cd $ROOT
echo [fastype] prepare spdlog v1.3.1 - done
echo [fastype] prepare boost boost-1.70.0
cd $ROOT/src/boost && git checkout tags/boost-1.70.0 && cd $ROOT
if [ ! -d src/boost/stage/lib ]; then
    cd $ROOT/src/boost && ./bootstrap.sh && ./b2 link=shared runtime-debugging=off runtime-link=shared variant=release -j8 && cd $ROOT
fi
echo [fastype] prepare boost boost-1.70.0 - done
echo [fastype] prepare icu4c release-64-2
cd $ROOT/src/icu && git checkout tags/release-64-2 && cd $ROOT
if [ ! -d src/icu/build ]; then
    cd $ROOT/src/icu && mkdir build && cd build && ../icu4c/source/runConfigureICU $OS && make -j8 && cd $ROOT
fi
echo [fastype] prepare icu4c release-64-2 - done

# build
DEBUG=debug
RELEASE=release
if [ ! -d $DEBUG ]; then mkdir $DEBUG; fi
if [ ! -d $RELEASE ]; then mkdir $RELEASE; fi
cd $DEBUG && cmake -DF_OS=$OS -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON ../src && make VERBOSE=1 && cd $ROOT
cd $RELEASE && cmake -DF_OS=$OS -DCMAKE_BUILD_TYPE=Release ../src && make -j8 && cd $ROOT
