[package]
name = "fastype"
version = "0.1.0"
authors = ["fastype <linrongbin16@outlook.com>"]

[lib]
name = "core"

[dependencies]
slog = "2"
slog-term = "2"
slog-async = "2"
slog-stdlog = "3"
slog-scope = "4"
log = "0.4"
