// Copyright 2019- <fastype.org>
// Apache License Version 2.0

#include "dsl/Type.h"
#include "Exception.h"
#include "Hasher.h"

namespace dsl {

icu::UnicodeString Type::name(int value) {
  switch (value) {
    // token type
  case FDSL_EOF:
    return UNICODE_STRING_SIMPLE("EOF");
  case FDSL_INTEGER:
    return UNICODE_STRING_SIMPLE("INTEGER");
  case FDSL_FLOATING:
    return UNICODE_STRING_SIMPLE("FLOATING");
  case FDSL_OPERATOR:
    return UNICODE_STRING_SIMPLE("OPERATOR");
  case FDSL_COMPARATOR:
    return UNICODE_STRING_SIMPLE("COMPARATOR");
  case FDSL_ASSIGNMENT:
    return UNICODE_STRING_SIMPLE("ASSIGNMENT");
  case FDSL_BOOLEAN:
    return UNICODE_STRING_SIMPLE("BOOLEAN");
  case FDSL_IDENTIFIER:
    return UNICODE_STRING_SIMPLE("IDENTIFIER");
  case FDSL_PUNCTUATION:
    return UNICODE_STRING_SIMPLE("PUNCTUATION");
  case FDSL_KEYWORD:
    return UNICODE_STRING_SIMPLE("KEYWORD");
  case FDSL_STRING:
    return UNICODE_STRING_SIMPLE("STRING");

    // ast type
  case FDSL_PROGRAM:
    return UNICODE_STRING_SIMPLE("PROGRAM");
  case FDSL_STATEMENT_LIST:
    return UNICODE_STRING_SIMPLE("STATEMENT_LIST");
  case FDSL_DECLARATION:
    return UNICODE_STRING_SIMPLE("DECLARATION");
  case FDSL_STATEMENT:
    return UNICODE_STRING_SIMPLE("STATEMENT");
  case FDSL_VARIABLE_DECLARATION:
    return UNICODE_STRING_SIMPLE("VARIABLE_DECLARATION");
  case FDSL_FUNCTION_DECLARATION:
    return UNICODE_STRING_SIMPLE("FUNCTION_DECLARATION");
  case FDSL_CLASS_DECLARATION:
    return UNICODE_STRING_SIMPLE("CLASS_DECLARATION");
  case FDSL_COMPOUND_STATEMENT:
    return UNICODE_STRING_SIMPLE("COMPOUND_STATEMENT");
  case FDSL_ASSIGNMENT_STATEMENT:
    return UNICODE_STRING_SIMPLE("ASSIGNMENT_STATEMENT");
  case FDSL_EMPTY_STATEMENT:
    return UNICODE_STRING_SIMPLE("EMPTY_STATEMENT");
  case FDSL_RETURN_STATEMENT:
    return UNICODE_STRING_SIMPLE("RETURN_STATEMENT");
  case FDSL_BINARY_OP:
    return UNICODE_STRING_SIMPLE("BINARY_OP");
  case FDSL_UNARY_OP:
    return UNICODE_STRING_SIMPLE("UNARY_OP");
  case FDSL_VARIABLE:
    return UNICODE_STRING_SIMPLE("VARIABLE");
  case FDSL_INTEGER_CONSTANT:
    return UNICODE_STRING_SIMPLE("INTEGER_CONSTANT");
  case FDSL_FLOATING_CONSTANT:
    return UNICODE_STRING_SIMPLE("FLOATING_CONSTANT");
  case FDSL_BOOLEAN_CONSTANT:
    return UNICODE_STRING_SIMPLE("BOOLEAN_CONSTANT");
  case FDSL_STRING_CONSTANT:
    return UNICODE_STRING_SIMPLE("STRING_CONSTANT");

    // symbol type
  case FDSL_BUILTIN_TYPE_SYMBOL:
    return UNICODE_STRING_SIMPLE("BUILTIN_TYPE_SYMBOL");
  case FDSL_VARIABLE_SYMBOL:
    return UNICODE_STRING_SIMPLE("VARIABLE_SYMBOL");
  case FDSL_FUNCTION_SYMBOL:
    return UNICODE_STRING_SIMPLE("FUNCTION_SYMBOL");
  default:
    FTHROW("type value not found:{}", value);
  }
}

std::string Type::utf8Name(int value) {
  std::string _1;
  return name(value).toUTF8String(_1);
}

int Type::value(const std::string &name) {
  static const std::unordered_map<std::string, int> typeMapping = {
      // token type
      {UNICODE_STRING_SIMPLE("EOF"), FDSL_EOF},
      {UNICODE_STRING_SIMPLE("INTEGER"), FDSL_INTEGER},
      {UNICODE_STRING_SIMPLE("FLOATING"), FDSL_FLOATING},
      {UNICODE_STRING_SIMPLE("OPERATOR"), FDSL_OPERATOR},
      {UNICODE_STRING_SIMPLE("COMPARATOR"), FDSL_COMPARATOR},
      {UNICODE_STRING_SIMPLE("ASSIGNMENT"), FDSL_ASSIGNMENT},
      {UNICODE_STRING_SIMPLE("BOOLEAN"), FDSL_BOOLEAN},
      {UNICODE_STRING_SIMPLE("IDENTIFIER"), FDSL_IDENTIFIER},
      {UNICODE_STRING_SIMPLE("PUNCTUATION"), FDSL_PUNCTUATION},
      {UNICODE_STRING_SIMPLE("KEYWORD"), FDSL_KEYWORD},
      {UNICODE_STRING_SIMPLE("STRING"), FDSL_STRING},

      // ast type
      {UNICODE_STRING_SIMPLE("PROGRAM"), FDSL_PROGRAM},
      {UNICODE_STRING_SIMPLE("STATEMENT_LIST"), FDSL_STATEMENT_LIST},
      {UNICODE_STRING_SIMPLE("DECLARATION"), FDSL_DECLARATION},
      {UNICODE_STRING_SIMPLE("STATEMENT"), FDSL_STATEMENT},
      {UNICODE_STRING_SIMPLE("VARIABLE_DECLARATION"),
       FDSL_VARIABLE_DECLARATION},
      {UNICODE_STRING_SIMPLE("FUNCTION_DECLARATION"),
       FDSL_FUNCTION_DECLARATION},
      {UNICODE_STRING_SIMPLE("CLASS_DECLARATION"), FDSL_CLASS_DECLARATION},
      {UNICODE_STRING_SIMPLE("COMPOUND_STATEMENT"), FDSL_COMPOUND_STATEMENT},
      {UNICODE_STRING_SIMPLE("ASSIGNMENT_STATEMENT"),
       FDSL_ASSIGNMENT_STATEMENT},
      {UNICODE_STRING_SIMPLE("EMPTY_STATEMENT"), FDSL_EMPTY_STATEMENT},
      {UNICODE_STRING_SIMPLE("RETURN_STATEMENT"), FDSL_RETURN_STATEMENT},
      {UNICODE_STRING_SIMPLE("BINARY_OP"), FDSL_BINARY_OP},
      {UNICODE_STRING_SIMPLE("UNARY_OP"), FDSL_UNARY_OP},
      {UNICODE_STRING_SIMPLE("VARIABLE"), FDSL_VARIABLE},
      {UNICODE_STRING_SIMPLE("INTEGER_CONSTANT"), FDSL_INTEGER_CONSTANT},
      {UNICODE_STRING_SIMPLE("FLOATING_CONSTANT"), FDSL_FLOATING_CONSTANT},
      {UNICODE_STRING_SIMPLE("BOOLEAN_CONSTANT"), FDSL_BOOLEAN_CONSTANT},
      {UNICODE_STRING_SIMPLE("STRING_CONSTANT"), FDSL_STRING_CONSTANT},

      // symbol type
      {UNICODE_STRING_SIMPLE("BUILTIN_TYPE_SYMBOL"), FDSL_BUILTIN_TYPE_SYMBOL},
      {UNICODE_STRING_SIMPLE("VARIABLE_SYMBOL"), FDSL_VARIABLE_SYMBOL},
      {UNICODE_STRING_SIMPLE("FUNCTION_SYMBOL"), FDSL_FUNCTION_SYMBOL},
  };
  auto it = typeMapping.find(name);
  if (it == typeMapping.end()) {
    FTHROW("dsl type name not found:{}", name);
  }
  return it->second;
}

} // namespace dsl
